//Register User
POST http://www.localhost:3500/api/user/register/
Content-Type: application/json

{
    "email": "tuananh@gmail.com",
    "password": "tuananh"
}

###
//Auth user
POST http://www.localhost:3500/api/user/auth/
Content-Type: application/json

{
    "email": "tuananh@gmail.com",
    "password": "tuananh"
}

###
//Test verify token
GET http://www.localhost:3500/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidHVhbmFuaEBnbWFpbC5jb20iLCJ1c2VySWQiOiI2OTQ5M2UyNDljYzA3ZDIyN2ViNzhlMTcifSwiaWF0IjoxNzY2NDA3NzI5LCJleHAiOjE3NjY0MDgzMjl9.OO0ZAnRSOcaBp_801RpIr-O9AsMYtl3RY09YvBATR5s


###
//Refresh accesstoken
GET http://www.localhost:3500/api/user/refresh/


